FROM ubuntu:14.04
ADD webapp/app/requirements.txt /tmp/
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y -q python-all python-pip
RUN pip install --upgrade pip && \
    pip install -r /tmp/requirements.txt
ADD /webapp /opt/webapp/
EXPOSE 5000
CMD ["python", "app/app.py"] 


    
